### CYTTSP
obj-$(CONFIG_TOUCHSCREEN_CYTTSP4) += cyttsp4_bus.o cyttsp4_core.o cyttsp4_devtree.o cyttsp4_i2c.o
cyttsp4_bus-objs = cyttsp4_btn.o cyttsp4_debug.o cyttsp4_device_access.o cyttsp4_loader.o cyttsp4_mt_common.o cyttsp4_mta.o cyttsp4_mtb.o cyttsp4_platform.o cyttsp4_samsung_sysfs.o
cyttsp4_core-objs = cyttsp4_btn.o cyttsp4_debug.o cyttsp4_device_access.o cyttsp4_loader.o cyttsp4_mt_common.o cyttsp4_mta.o cyttsp4_mtb.o cyttsp4_platform.o cyttsp4_samsung_sysfs.o
cyttsp4_devtree-objs = cyttsp4_btn.o cyttsp4_debug.o cyttsp4_device_access.o cyttsp4_loader.o cyttsp4_mt_common.o cyttsp4_mta.o cyttsp4_mtb.o cyttsp4_platform.o cyttsp4_samsung_sysfs.o
cyttsp4_i2c-objs = cyttsp4_btn.o cyttsp4_debug.o cyttsp4_device_access.o cyttsp4_loader.o cyttsp4_mt_common.o cyttsp4_mta.o cyttsp4_mtb.o cyttsp4_platform.o cyttsp4_samsung_sysfs.o

#CFLAGS_cyttsp4_core.o += -DDEBUG

